module Server {
    interface EntryGate {
        readonly attribute string machine_name;
        void turn_on(in string machine_name);
        void turn_off();
        void reset(in string machine_name);
    };
};
