module Server {
    interface ExitGate {
        readonly attribute string machine_name;
        readonly attribute boolean turned_on;
        void turn_on(in string machine_name, in string machine_ior);
        void turn_off();
        void reset(in string machine_name, in string machine_ior);
        void vehicle_out(in string car_registration);
    };
};
